# Generated by Django 4.1.4 on 2023-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/noimg.png', upload_to='images/'),
        ),
    ]
